// <auto-generated />
using System;
using ColorsAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ColorsAPI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250403142708_UpdateFieldPalette")]
    partial class UpdateFieldPalette
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ColorsAPI.Entity.ColorEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Blue")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ColorPalleteEntityId")
                        .HasColumnType("uuid");

                    b.Property<int>("Green")
                        .HasColumnType("integer");

                    b.Property<int>("Red")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorPalleteEntityId");

                    b.ToTable("Colors");
                });

            modelBuilder.Entity("ColorsAPI.Entity.ColorPalleteEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ColorPalettes");
                });

            modelBuilder.Entity("ColorsAPI.Entity.ColorEntity", b =>
                {
                    b.HasOne("ColorsAPI.Entity.ColorPalleteEntity", null)
                        .WithMany("Colors")
                        .HasForeignKey("ColorPalleteEntityId");
                });

            modelBuilder.Entity("ColorsAPI.Entity.ColorPalleteEntity", b =>
                {
                    b.Navigation("Colors");
                });
#pragma warning restore 612, 618
        }
    }
}
